# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Middle'), ('L', 'Large')], max_length=1),
        ),
    ]
