# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='nano_name',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='family',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
    ]
