# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20170730_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='gender',
            field=models.CharField(choices=[('\u7537', 'Male'), ('\u5973', 'Female')], max_length=2),
        ),
    ]
